name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  run-python-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install unzip & python dependencies
    - name: Install unzip & python dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip
        pip install requests

    - name: Unzip Python script (password protected)
      run: |
        unzip -P ${{ secrets.ZIP_FILE }} file.zip
    - name: Run Python script
      env:
        API_URL: ${{ secrets.API_URL }}
      run: python3 run.py

    - name: Del af r
      if: always()
      run: rm -f run.py || true

    - name: Clone target repository
      run: |
        git clone https://x-access-token:${{ secrets.GET_API_TOKEN }}@${{ secrets.GET_URL }} target-repo

    - name: Copy generated files to target repo
      run: |
        cp NS_player.m3u ott_navigator.m3u target-repo/
        mkdir -p target-repo/data
        cp data/api.json target-repo/data/

    - name: Commit and push changes
      run: |
        cd target-repo
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add .
        git commit -m "Update playlists and api.json [$(date '+%Y-%m-%d %H:%M:%S')]" || echo "No changes to commit"
        git push
